[tool.poetry]
name = "binary_wheel_builder"
version = "0.1.0"
description = "Binary wheel builder"
authors = ["Timo Reymann <timo.reymann@deepl.com>"]
readme = "README.md"
packages = [
    { include = "binary_wheel_builder" }
]
[tool.poetry.dependencies]
python = "> 3.8"
wheel = "> 0.30.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
